### ISSUE TITLE
Helm Hook

### ISSUE THREAD

**Issue by usrlocalang** [replicatedhq/kots#1145]
I see from the code that the kots application only handles Helm Hooks on Jobs? 

[Handles Only Jobs Hooks](https://github.com/replicatedhq/kots/commit/42b8be42c4c03207db125b2a0c351d9611350e14#diff-0af46d71841c043aeb4c57f0bea270e5R63)

I don't see this covered in the documentation. Maybe I missed it?  We have K8s Jobs in a HelmChart that has hooks. So we wanted to be sure that kots would run the hooks in the specific weighted order.

**Comment by AmberAlston** [comment]
KOTS now supports Helm hooks and weights, so going to close this older issue out. Associated docs - https://docs.replicated.com/vendor/helm-installing-native-helm
