### ISSUE TITLE
Multi-arch images for kotsadm

### ISSUE THREAD

**Issue by blampe** [replicatedhq/kots#1419]
Are there any plans to publish admin console images with arm64 support?

Currently, running `kots install` on an ARM cluster will result in crashloopbackoffs with

> exec user process caused "exec format error"

due to the arch mismatch.

**Comment by obfuscurity** [comment]
Sorry for the slow response. I don't have an ETA for you at this time, but we do have an internal tracking story (SC34569) for ARM support that Replicated customers can reference with their account representative.
