### ISSUE TITLE
No binaries for arm

### ISSUE THREAD

**Issue by BretFisher** [replicatedhq/kots#1670]
Due to the increasing number of Kubernetes users on arm platforms, I'm requesting the following build targets be added to releases:

darwin/arm64  (Apple M1)
linux/arm64     (AWS Graviton and some 64-bit Raspberry Pi's)
linux/arm          (Most Raspberry Pi's, 32-bit v7 arch)

Thanks!

**Comment by obfuscurity** [comment]
Sorry for the slow response. I don't have an ETA for you at this time, but we do have an internal tracking story (SC34569) for ARM support that Replicated customers can reference with their account representative.

**Comment by philCryoport** [comment]
FYI @BretFisher per [the docs as of this writing (18OCT2024)](https://docs.replicated.com/enterprise/installing-general-requirements#minimum-system-requirements):

```
Supported operating systems: The following are the supported operating systems for nodes:
- Linux AMD64
- **_Linux ARM64_**

```

**Comment by BretFisher** [comment]
Sweet, thanks!
