### ISSUE TITLE
minio init process is unneeded after migrations completes

### ISSUE THREAD

**Issue by laverya** [replicatedhq/kots#177]
In some future version (1.7?) we should remove the initcontainer for minio added as part of https://github.com/replicatedhq/kots/pull/175. It's only required for the first run after upgrading from <=1.4, and so as long as kots is started once on 1.5/1.6, 1.7 would be able to forgo it entirely.

**Comment by marccampbell** [comment]
👍1.7.0 feels like a good release to remove this, thanks!

**Comment by laverya** [comment]
bumping for 1.9.0

**Comment by marccampbell** [comment]
@laverya is this still an open item?
