### ISSUE TITLE
Description in Cluster Management is inverted

### ISSUE THREAD

**Issue by MikaelSmith** [replicatedhq/kots#1781]
The description of used resources is wrong, it appears to be inverted from what's actually true.

<img width="1007" alt="Screen Shot 2021-04-16 at 10 43 27 AM" src="https://user-images.githubusercontent.com/8162496/115063896-0b36dc00-9ea1-11eb-9eeb-af25aeecdb04.png">

When I `kubectl describe node` and `kubectl top node`, I get things like
- centos-c has 14 pods running
- centos-a is using ~1.5 CPU cores
- centos-b is using ~6 GB memory

Something like “x of y available” could make sense, but “x used of y available” is wrong.

**Comment by AmberAlston** [comment]
I created a CH story for this - #32903

**Comment by tamarahenson** [comment]
Internal Request #32998 has been logged.  -TH

**Comment by MikaelSmith** [comment]
Fixed in 1.40.0.
