### ISSUE TITLE
useHelmInstall doesn't work outside the default namespace

### ISSUE THREAD

**Issue by BretFisher** [replicatedhq/kots#2404]
I've tried Native Helm with the latest kotsadm v1.58.1 and it's broken with image pull secrets in non-default namespaces.

When kurl and kots are set to install an app called `app-name` in the `custom` namespace. A working non-native helm install (`useHelmInstall: false`) shows this secret in `custom` namespace: `<app-name>-registry  kubernetes.io/dockerconfigjson`

When I add `useHelmInstall: true` to `helmChart`, that secret doesn't exist in the `custom` namespace, and it seems image pull secrets are only in the `default` namespace. The secret name changes as well: `<app-name>-<namespace>-registry  kubernetes.io/dockerconfigjson`

Our kurl is set to:

```yaml
kotsadm:
    applicationNamespace: custom
```

and our kots Application resource is set to:

```yaml
additionalNamespaces:
    - '*'
```

## Workaround

`useHelmInstall: true` works if we only use the `default` namespace, so we're rolling back our custom namespace install for now.

**Comment by jeffreygolden** [comment]
Hey Bret,

I see an internal story that resolved this issue in 1.59.0. Here's a link to the PR if you're interested: https://github.com/replicatedhq/kots/pull/2405
