### ISSUE TITLE
I can't install instaloadet in python with pip 

### ISSUE THREAD

**Issue by Aminrtp** [replicatedhq/kots#3061]
I can't install instaloader madule in python with pip 
It installed but when I use it in pycharm received madule not found error

**Comment by sgalsaleh** [comment]
@Aminrtp could you please elaborate on:

- what are the steps you're taking?
- what are you expecting to happen?
- what is actually happening?

are you trying to update one of the Dockerfiles to install the `instaloadet` package?

**Comment by cbodonnell** [comment]
Hi @Aminrtp, I'm going to close out this issue since we have not heard back.  Please re-open it if you have any additional details you can share.
