### ISSUE TITLE
cannot open admin console. Error: Client.Timeout exceeded while awaiting headers

### ISSUE THREAD

**Issue by kushal-ti** [replicatedhq/kots#3554]
I have a kots application installed on a cluster. The admin console pod is running and healthy. 

If i run 
```bash
kubectl kots admin-console --namespace kots-app --port 3000
```
I get 
```bash
Error: failed to port forward: failed to query healthz: Get "http://localhost:3000/healthz": context deadline exceeded (Client.Timeout exceeded while awaiting headers)
```

But if i open a portforward to the kotsadm pod at 3000 and curl http://localhost:3000/healthz, I get the following response
```
{"version":"v1.92.1","gitSha":"test","status":{"database":{"connected":true},"storage":{"available":true}}}
```

Don't know how to solve this issue, any help would be greatly appreciated

**Comment by garcialuis** [comment]
Hi @kushal-ti I am starting to look into this. In the meantime can you [generate a support bundle](https://community.replicated.com/t/kots-how-can-i-generate-a-support-bundle-if-i-cannot-access-the-admin-console/455) and share it here please? This will give me more information about the current state of the cluster to continue troubleshooting. Thank you

**Comment by kushal-ti** [comment]
Hi. I know this is not exactly helpful, but this problem was solved when i switched environments. I was initially trying it on a local mac, which failed as described above, then tried the same thing from an online IDE (gitpod) and it worked. I'm not sure what the bug was, but if i had to guess, there was some kind of misconfiguration with the networking settings on my local machine, not something inherent to the replicated app itself

**Comment by obfuscurity** [comment]
No problem, thanks for the update. We're going to close this out but please report back if you run into this again.
