### ISSUE TITLE
KOTS CLI: admin-console command: Allow specifying port if 8800 is taken, or using --port 0 to use any unused port

### ISSUE THREAD

**Issue by dexhorthy** [replicatedhq/kots#390]
right now, if you do a cluster install you need to have port 8800 open on your workstation to fire up the port-forward

```
Enter the namespace to deploy to: kots-dex
  • Deploying Admin Console
    • Creating namespace ✓  
    • Waiting for datastore to be ready ✓  
Enter a new password to be used for the Admin Console: ••••••••
  • Waiting for Admin Console to be ready ✓  
Error: failed to forward port: unable to listen on any of the requested ports: [{8800 3000}]
```

Two issues here:

1. no flag to set the port, and no way to say "just get any port"
2. No information is presented about how to fix, or what to do next (e.g. `When this is resolved, run kubectl kots admin-console -n kots-dex to connect to the admin console` or `run kubectl kots admin-console -n kots-dex --port PORT` to connect to the admin console on a different port)

**Comment by marccampbell** [comment]
See #171

**Comment by marccampbell** [comment]
Added in #412
