### ISSUE TITLE
Unable to `kots upstream upgrade --deploy-version-label` 

### ISSUE THREAD

**Issue by gbarna-bd** [replicatedhq/kots#4010]
The admin console is showing me only the currently deployed version and the latest, but I am looking for an intermediate version.
I've tried running upstream upgrade, but I'm getting an error:
```bash
kubectl kots -n $ns upstream upgrade $appSlug --deploy-version-label $appVersion
  • Checking for application updates ✗  
  • Unexpected response from the API: 500
```
It only seems to work with the versions available in the admin console (the currently deployed one and the latest).

Did I misread the docs and the command above doesn't fetch application versions from the Replicated vendor? If so, is there any way of getting a specific version?
Thanks.

**Comment by gbarna-bd** [comment]
Hi. Thank you for your reply.
After more troubleshooting, I realized that `kots upstream upgrade` (and its UI equivalent) are working as expected, but the Vendor's license was unpinned and so it would only pull the latest.
Sorry for the confusion and thanks again!

**Comment by cbodonnell** [comment]
You're welcome. Glad things are working as expected!

/close
