### ISSUE TITLE
Add support for Oracle Kubernetes Engine (OKE) in the distribution list

### ISSUE THREAD

**Issue by jasonmccampbell** [replicatedhq/kots#4116]
We are adding support for Oracle's cloud infrastructure service and need to be able to detect their OKE as an installation target. We would OKE to be detected and present in the distribution enum similar to AKS and EKS.

More specifically:
* The primary goal is that the distribution is available in the templating so we can generate resources customized to Oracle Cloud Infrastructure: `{{- if eq .Values.kubernetes_distribution "oke" }}`
* Secondarily, OKE should be supported on par with other distributions (EKS, AKS, minikube, etc) if possible to avoid introducing developer traps with incomplete support.

**Comment by cbodonnell** [comment]
@jasonmccampbell we merged https://github.com/replicatedhq/kots/pull/4119 with this change and the updated troubleshoot module. it will be available in the next patch release of KOTS. thanks for the contribution!
