### ISSUE TITLE
HelmChart spec, exclude field should be a BoolString, not a string

### ISSUE THREAD

**Issue by marccampbell** [replicatedhq/kots#443]
It would allow more flexibility in templating this field:

https://github.com/replicatedhq/kots/blob/master/kotskinds/apis/kots/v1beta1/helmchart_types.go#L240

**Comment by cbodonnell** [comment]
This has been completed.  The field is now a `multitype.BoolOrString`: https://github.com/replicatedhq/kots/blob/v1.90.0/kotskinds/apis/kots/v1beta1/helmchart_types.go#L356
