### ISSUE TITLE
Support decrypted ConfigValues in kots download/upload

### ISSUE THREAD

**Issue by marccampbell** [replicatedhq/kots#451]
Currently, `kots download` returns the user-supplied config values in `upstream/userdata/config.yaml`. This is an internally-generated file with GVK `kots.io/v1beta1, Kind=ConfigValues`. This file can be edited and then uploaded with `kots upload` and KOTS will regenerate the base with the new values.

However, if a config item type is "password", the value is encrypted, making it very difficult to update.

A possible solution here is for `kots download` to return the password types decrypted, and then `kots upload` can receive the decrypted/updated value and re-encrypt before saving.

To facilitate this, the `ConfigValue` spec should be extended to support both `value` and `valuePlaintext`. If a value is supplied in `kots upload` in `valuePlaintext`, it will be assumed to overwrite the currently encrypted.

`kots download` should not include the decrypted values by default, unless a flag is passed to include them. 

This change will enable automated workflows that are not currently possible today.

**Comment by dexhorthy** [comment]
👍 🙏

**Comment by dexhorthy** [comment]
@marccampbell can we update this to describe what happens when both `value` and `valuePlaintext` are uploaded in an item?

Also a little clarity around flag behavior would be great, maybe something like

> if `--decrypt-password-values` is passed, `userdata/config.yaml` will contain only `valuePlaintext` for `password` type values, and `value` will be empty or absent entirely

**Comment by marccampbell** [comment]
I think in this case, the `valuePlaintext` would replace `value`.

**Comment by marccampbell** [comment]
this was added in replicatedhq/kotsadm#1385 also
