### ISSUE TITLE
Unable to install using '--license-file' on the CLI

### ISSUE THREAD

**Issue by MikaelSmith** [replicatedhq/kots#455]
```
$ kubectl kots install cd4pe/unstable --license-file license.yaml
Enter the namespace to deploy to: cd4pe

  • Pulling upstream ✓
  • Creating base ✓
  • Creating midstream ✓
  • Creating downstream "this-cluster" ✓
  • Deploying Admin Console
    • Creating namespace ✓
    • Waiting for datastore to be ready ✓
Enter a new password to be used for the Admin Console: ••••••••••
  • Waiting for Admin Console to be ready ✓
Application name: kotsadm042477586
  • Uploading local application to Admin Console ✗
Error: failed to unmarshal response: invalid character '<' looking for beginning of value
```
The same seems to work fine if I omit `--license-file` and use the same file in the console workflow.

My goal is to install the application without GUI intervention.

**Comment by dexhorthy** [comment]
Thanks @MikaelSmith ! We'll check this out --cc @areed , I think this error is fixed by #454 ?

I know there's still an issue with the --license-file still prompting in the UI so maybe lets leave this open until we can triage that side of it.

**Comment by marccampbell** [comment]
This is fixed by #450 because the workflow here has changed. Currently, evidenced by the output in this issue, when a license file is provided on the CLI, KOTS pulls and packages the application. This is not the desired workflow. Instead, with #450, KOTS will run a normal install workflow, but put the license file from the CLI into a ConfigMap with a label that the Admin Console will find on start and pull in.

**Comment by MikaelSmith** [comment]
I guess the unclear part in what I want is how to provide config for the application.

**Comment by marccampbell** [comment]
@MikaelSmith there's still an open issue with #451 that's related here, I think. That issue specifically is about sending encryption in `ConfigValues` when sending to/receiving from the server.

Would it make sense to have a locally available YAML document that is the `kots.io/v1beta1, kind=ConfigValues` with the values, and be able to:

```
kubectl kots install app --license-file ./license.yaml --config-values ./configvalues.yaml
```
?

**Comment by MikaelSmith** [comment]
Yeah, that's along the lines of what I was imagining.

**Comment by marccampbell** [comment]
The last part here is to include the `--config-values` flag on the `install` command.

**Comment by marccampbell** [comment]
This looks complete for 1.15.0 -- docs pending to be merged for release: https://github.com/replicatedhq/kots.io/pull/180/files
