### ISSUE TITLE
Adding a master node with kURL and kubernetes 1.17.3 fails

### ISSUE THREAD

**Issue by MikaelSmith** [replicatedhq/kots#522]
While trying to add a master node to an HA cluster using the command under the "Add a Node" section
```
curl -sSL https://kurl.sh/app-slug/join.sh | sudo bash -s \
  kubernetes-master-address=192.168.0.1:6443 \
  kubeadm-token=a.bunch.of.stuff \
  kubeadm-token-ca-hash=sha256:06dbff5bfc8892fe98d5576061a0c4b03492c71de1c4be300a40f50a0d4be8d1 \
  docker-registry-ip=10.96.2.200 \
  kubernetes-version=v1.17.3 \
  cert-key=c53c9a0170101fc296f21ff9c4dd697fc2c8c216264324f03ee4fcd4d3083aab \
  control-plane
```
I got an error
```
⚙  Addon ekco 0.2.3
tar: This does not look like a tar archive

gzip: stdin: not in gzip format
tar: Child returned status 1
tar: Error is not recoverable: exiting now
```
It also left behind a file
```
$ cat kubernetes-v1.17.3.tar.gz
<?xml version="1.0" encoding="UTF-8"?>
<Error><Code>AccessDenied</Code><Message>Access Denied</Message><RequestId>C7CD5FF091792206</RequestId><HostId>UY5jAZFZC+5p0+WK8/k/k+6j760lvhZcSOo2UMpzFioo/p76Cjjo68sj+TI9VkB+ELwGwNvL1kw=</HostId></Error>
```

It appears to be trying to download from https://kurl-sh.s3.amazonaws.com/dist/kubernetes-v1.17.3.tar.gz, which I've been told shouldn't have a `v` in the version. The `join.sh` initializes `KUBERNETES_VERSION="1.17.3"`.

This string is from the Admin Console (the "Worker Node" and "Master Node" instructions both include `v1.17.3`) at https://github.com/replicatedhq/kots/blob/master/kotsadm/pkg/kurl/node_join.go#L55, which seems to pull in server version. When I check that with `kubectl version` I get
```
Server Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.3", GitCommit:"06ad960bfd03b39c8310aaf92d1e7c12ce618213", GitTreeState:"clean", BuildDate:"2020-02-11T18:07:13Z", GoVersion:"go1.13.6", Compiler:"gc", Platform:"linux/amd64"}
```
which I believe explains how it got `v1.17.3`.

I've worked around this by changing the command to use `kubernetes-version=1.17.3`.

**Comment by dexhorthy** [comment]
@MikaelSmith thanks for the issue -- I believe a fix is on the way.

**Comment by areed** [comment]
Fixed in https://github.com/replicatedhq/kURL/pull/445
