### ISSUE TITLE
Should kotsadm periodically check for updates in the background?

### ISSUE THREAD

**Issue by dexhorthy** [replicatedhq/kots#528]
Right now to fetch a new version you need to "check for updates" under the version history tab or with the kots CLI.

Is there any intention to have kotsadm check for updates on a regular cadence? Perhaps one that is configurable/disable-able by the user?

Among other benefits, this seems fairly essential for any sort of gitops workflow to be valuable and eliminate manual actions that aren't merging PRs.

**Comment by bytniak** [comment]
This looks ready to solve the issue => #524

**Comment by dexhorthy** [comment]
@bytniak  @AbrahamAlcaina looks like this is in, scheduled for release in KOTS 1.16.0

**Comment by AbrahamAlcaina** [comment]
@dexhorthy  Is it fixed in the 1.16 release?
