### ISSUE TITLE
`kots download` fails with "error opening tar archive for reading"

### ISSUE THREAD

**Issue by fshot** [replicatedhq/kots#56]
After specifying a valid namespace & destination folder, `kots download` consistently results in the following error:

```
  • Connecting to cluster ⠦Error: opening tar archive for reading: wrapping file reader: unexpected EOF
opening tar archive for reading: wrapping file reader: unexpected EOF
```

**Comment by marccampbell** [comment]
@fshot i'm unable to reproduce this...  Do you have an example command that's returning this?

**Comment by fshot** [comment]
Aha, yes, @marccampbell - I see this issue when I fail to specify an app-slug.  When I provide an app-slug, download works fine.

Is app-slug required?  CLI doesn't currently enforce it.
