### ISSUE TITLE
Previous versions of statefulsets not getting deleted

### ISSUE THREAD

**Issue by yuvraj9** [replicatedhq/kots#560]
If I change name of a stateful set then the new one gets deployed but the old one still doesnt get deleted. Same happens for lots of other resources. It shows in diff that the resource is getting removed but in cluster the resources stays.

**Comment by emosbaugh** [comment]
@yuvraj9 could you share the statefulset spec metadata? is there a namespace specified? im wondering if it is related to this recently closed issue https://github.com/replicatedhq/kots/issues/564 . thanks

**Comment by yuvraj9** [comment]
@emosbaugh  Yes It has namespace specified. We are using helm charts and specifying namspace in the **HelmChart** manifest

**Comment by mzaneri** [comment]
@ yuvraj9 I see this was closed and re-opened- are you stilling running into this?

**Comment by yuvraj9** [comment]
its working now
