### ISSUE TITLE
StatusInformers do not work across Namespaces

### ISSUE THREAD

**Issue by dexhorthy** [replicatedhq/kots#578]
I've implemented [StatusInformers](https://kots.io/reference/v1beta1/application/#statusinformers) for the multi-namespace app listed in replicatedhq/kotsadm#1352, but they do not appear to detect when the nginx pod in the `hardcoded` namespace becomes ready.

**Comment by dexhorthy** [comment]
cc @allanyung

**Comment by marccampbell** [comment]
Closing this as it's been fixed
