### ISSUE TITLE
Developer Environment: Easy way to hard-code kotsadm image tags?

### ISSUE THREAD

**Issue by dexhorthy** [replicatedhq/kots#585]
When developing KOTS features, it may sometimes be useful to use a development build of a kotsadm or kotsadm-api when developing changes to something like `kots install`. From what I can tell, there are build tags for changing kotsadm image tags/registries, but i wanted to propose an either way to do this at runtime, perhaps via something like 

```
--kotsadm-api-image=gcr.io/my-project/kotsadm-api:my-tag \
--kotsadm-image=...
```

or via env vars

```
KOTSADM_API_IMAGE=...
```

Thoughts? Am I missing an easier way to do this?

**Comment by dexhorthy** [comment]
ping @divolgin @emosbaugh @laverya @areed @mzaneri

**Comment by divolgin** [comment]
@dexhorthy try this script https://github.com/replicatedhq/kots/blob/master/kotsadm/build-ttl.sh

**Comment by laverya** [comment]
I'm confused - do you want a way to run `kots install` with a custom image/tag? Because that already exists: https://github.com/replicatedhq/kots/blob/8ca1807/cmd/kots/cli/install.go#L196

`kubectl kots install --kotsadm-tag=alpha`, for example

**Comment by dexhorthy** [comment]
@laverya let me try with those flags, I had tried with build tags but missed these.

**Comment by marccampbell** [comment]
@dexhorthy was this solved with the --kotsadm-tag flag?

**Comment by dexhorthy** [comment]
@marccampbell I never got a chance to check but feel free to close for now (cc @salahalsaleh ) I'll circle back the next time I need to test this.

**Comment by salahalsaleh** [comment]
Thanks @dexhorthy, closing this for now.
