### ISSUE TITLE
Remove PG as a requirement

### ISSUE THREAD

**Issue by marccampbell** [replicatedhq/kots#614]
One of the primary design goals of kotsadm is to keep the footprint (security, memory, cpu, images) as small as possible. We want to ensure that that Admin Console is always smaller than the application footprint.

Currently postgres is hard to make HA and also hard to manage. Since our use of PG is small, what easier to manage options can we replace it with that is HA and has a smaller footprint?

**Comment by obfuscurity** [comment]
Tracking internally with SC epic 58485.

**Comment by cbodonnell** [comment]
As of v1.89.0, postgres is no longer a requirement for kots and has been replaced with rqlite: https://docs.replicated.com/release-notes/rn-app-manager#1890
