### ISSUE TITLE
License expiration isn't checked until after fetching application

### ISSUE THREAD

**Issue by MikaelSmith** [replicatedhq/kots#629]
For large applications - especially in airgap environments - uploading the app bundle can take several minutes. If you provided an expired license, you don't get feedback that it's expired until after the application is uploaded. Then once you get a valid license, you have to upload the application again.

Ideally feedback that the license is expired would happen immediately after uploading it.

**Comment by marccampbell** [comment]
@salahalsaleh will you take a look at this for 1.17?
