### ISSUE TITLE
Automated install fails to deploy with no preflight checks

### ISSUE THREAD

**Issue by emosbaugh** [replicatedhq/kots#632]
Automated install does not deploy with no preflights. Preflight spin forever with "Running checks". User has to manually click "Deploy".

<img width="1057" alt="Screen Shot 2020-06-02 at 7 50 17 PM" src="https://user-images.githubusercontent.com/371319/83590413-8c47e780-a50a-11ea-8d47-38515193579d.png">

**Comment by bytniak** [comment]
+1 Exactly the same behavior with preflight checks...

**Comment by dexhorthy** [comment]
@marccampbell @markpundsack can we confirm this is going in 1.17 ? I don't see any linked PRs

**Comment by markpundsack** [comment]
@dexhorthy Sounds like it. @salahalsaleh is working on it now. Linked to a partial fix above, but is working on the rest now.
