### ISSUE TITLE
Config Change reverts changes.

### ISSUE THREAD

**Issue by yuvraj9** [replicatedhq/kots#637]
If we do a config change then all our changes from past releases are getting reverted. It is also creating several releases for that one config change. I face this only when I make any config change. Later I have to make another release from vendor page which bring back the changes. Attaching image for this.
![Screenshot from 2020-06-04 14-04-44](https://user-images.githubusercontent.com/56301121/83734277-64709500-a66c-11ea-944b-fc52bf5c6a89.png)

**Comment by laverya** [comment]
Would you mind uploading a support bundle in the vendor console (https://vendor.replicated.com) or [here](https://help.replicated.com/support/)?

**Comment by yuvraj9** [comment]
@laverya Done. My support bundle request id is - `terribly-vast-macaw`

**Comment by laverya** [comment]
Thanks, let me take a look!

**Comment by laverya** [comment]
I've followed up in Slack
