### ISSUE TITLE
Use an internal Registry in a non-airgapped environment

### ISSUE THREAD

**Issue by dexhorthy** [replicatedhq/kots#654]
Currently, kotsadm can be configured to deploy using a user-hosted registry, writing YAML with kustomize to pull from the user-hosted registry instead of from the public internet. 

However, there is no way to do this in a non-airgapped environment, the images must be uploaded by a `.airgap` archive and unpacked and pushed from there. I'd like to start a discussion around enabling the push-to-my-registry-during-updates and pull-from-my-registry-at-runtime workflow for non-airgapped style installations, where images can be piped from a public registry into my internal registry with a single click (or better yet, automatically) without having to collect and transfer a `.airgap` archive to the instance.

This enables some pretty cool GitOps use cases as well 🙂

**Comment by marccampbell** [comment]
@dexhorthy If I understand properly, this is possible today. You can go to the Registry tag in the Admin Console view (even for an online install) and configure a "local" registry. If this is configured, all images will be retagged and pushed there, even for online installs.

Does this handle the workflows?

**Comment by dexhorthy** [comment]
@marccampbell @salahalsaleh it was my understanding that changing the registry setting in the admin console was not supported for non-airgapped installs.

**Comment by dexhorthy** [comment]
@marccampbell @salahalsaleh I just tested this on KOTS 1.16.1 and it appears to work well. Looks like this might have been related to a fix in 1.13.3? https://kots.io/release-notes/1.13.3/ 

anyhow feel free to close

**Comment by salahalsaleh** [comment]
Thanks @dexhorthy, closing this for now.
