### ISSUE TITLE
kots admin-console command hangs when incorrect namespace is specified

### ISSUE THREAD

**Issue by marccampbell** [replicatedhq/kots#67]
```
$ k kots admin-console asdasdasd
```

I'd expected this to return an error that application "asdasdasd" was not found. But currently it just hangs.

**Comment by cbodonnell** [comment]
closing this issue as the `kots admin-console` [command](https://docs.replicated.com/reference/kots-cli-admin-console-index) now uses a namespace instead of an application slug and will timeout after `10s` if the kotsadm pod is not found
