### ISSUE TITLE
Random key generation

### ISSUE THREAD

**Issue by MikaelSmith** [replicatedhq/kots#716]
I put up an issue and PR - https://github.com/Masterminds/sprig/issues/252 - to add a `randBytes` function to Sprig that creates a base64-encoded sequence of random bytes. This is useful for generating a cryptographically random secret for certain applications.

Sprig doesn't seem to update often. Would you be open to adding this to KOTS' templates in the meantime?

**Comment by dexhorthy** [comment]
@MikaelSmith today we have `RandomString`, e.g. `{{repl RandomString 32 | Base64Encode}}` -- this is based on `crypto/rand` from the go stdlib, does this meet your needs?

**Comment by MikaelSmith** [comment]
I'll take a look, I wasn't sure it used the whole character range.

**Comment by MikaelSmith** [comment]
I'm currently using randAscii from Sprig. That only uses 7-bits for randomness, and because Regexp is based on UTF-8 I don't think it can do any better (need that 8th bit for multi-byte characters). For example https://play.golang.org/p/ULtd6Ij-Nur returns an error because it's not valid UTF-8.

**Comment by MikaelSmith** [comment]
I could modify RandomString to fall-back to a range of bytes if given invalid characters, but that seems a bit obtuse.

**Comment by marccampbell** [comment]
I don't see any downside to adding a `RandomBytes` complement to `RandomString`

**Comment by MikaelSmith** [comment]
I haven't gotten any comment on the sprig PR, so I'll move it over here.
