### ISSUE TITLE
Ability to perform automated installs in a kURL embedded cluster

### ISSUE THREAD

**Issue by dexhorthy** [replicatedhq/kots#884]
It would be great to be able to completely automate the setup of kots in an embedded kURL cluster, the same way is possible with [Automated Installations](https://www.google.com/search?q=site%3Akots.io+automating) into existing clusters today. This would mean eliminating the following manual browser steps from the install process for kURL+kotsadm:

- uploading license
- supply Config values
- reviewing preflight check results

Right now, when using the kotsadm addon for https://kurl.sh, kotsadm gets wired up to the rook RGW in a special way that's not possible to replicated today using `kots install`.

This means that if you were to run a `kubectl kots install` against a kurl cluster with kotsadm already installed, you end up with minio and an extra copy of the migration job. While not technically a blocker, I get the feeling this is not officially endorsed by the kots/kurl team.

Do we have any intentions for allowing automated installs in an officially supported way?

**Comment by divolgin** [comment]
@dexhorthy isn't this the same as #809

**Comment by dexhorthy** [comment]
@divolgin good catch, will close as dupe of #809
