### ISSUE TITLE
Helm Charts not updating with kots-cli

### ISSUE THREAD

**Issue by nabt** [replicatedhq/kots#903]
Using the following process to modify a resultant deployment set in an existing KOTS app deployed via `kurl.sh` does not update the chart files for the deployment:

- Download kots config
```
kubectl kots download -n default --slug [app_name] --dest ./
```
- Modify Helm CRD in `./[app_name]/upstream`
- Upload kots config for deployment
```
kubectl kots upload -n default --slug [app_name] [full_path_to_downloaded_config]
```

Expected Result:  The new values in the Helm Chart CRD would be reflected in the `base` files when deployed and viewed in the _View Files_ tab of the Kotsadm console.

Result:  Nothing has changed in the deployment files in the `base/charts/[chart_name]/` file location.

The same process works if deployed by creating a release in the vendor portal via the Replicated CLI.

**Comment by laverya** [comment]
possibly related to https://github.com/replicatedhq/kots/issues/479

**Comment by nabt** [comment]
UPDATE: Making any change to a setting in the _Config_ tab, saving, and deploying forces the re-evaluation of the stack, and applies the changes.  All testing was done on version `1.17.2`.  So, I believe just making this happen automatically when a deployment is initiated via the `kots upload` command is all that is needed to resolve the issue.
