### ISSUE TITLE
Ability to customize favicon

### ISSUE THREAD

**Issue by MikaelSmith** [replicatedhq/kots#947]
I'd like to be able to customize the favicon to match our logo.

Currently it uses a KOTS icon
<img width="654" alt="Screen Shot 2020-08-14 at 9 53 40 AM" src="https://user-images.githubusercontent.com/8162496/90273662-2cc45d00-de14-11ea-9456-989fb327579a.png">

**Comment by dexhorthy** [comment]
I think this might be pulled from the application metadata now, but need to verify what version that fix was in

**Comment by MikaelSmith** [comment]
Does look that way.

**Comment by ajp-io** [comment]
Closing this since the favicon is pulled from the application metadata.
