### ISSUE TITLE
K8s Admin usability: Kotsadm component service names don't match deployment names

### ISSUE THREAD

**Issue by dexhorthy** [replicatedhq/kots#958]
This is a pretty minor thing, but it seems like Kubernetes convention is for Service names to match Deployment names. We have, for deployments

```
NAME               READY   UP-TO-DATE   AVAILABLE   AGE
kotsadm            1/1     1            1           5h4m
kotsadm-api        1/1     1            1           5h4m
```

but the service name for kotsadm-api doesn't match:

```
NAME               TYPE        CLUSTER-IP      EXTERNAL-IP   PORT(S)    AGE
kotsadm            ClusterIP   10.31.240.190   <none>        3000/TCP   5h4m
kotsadm-api-node   ClusterIP   10.31.244.43    <none>        3000/TCP   5h4m
```

**Comment by marccampbell** [comment]
@dexhorthy this is intentional. As we are working to remove the NodeJS deployment and service, those will be deleted and `kotsadm` deployment and service name will remain. These legacy, internal names are ok and in the process of being removed
